### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/computer-science-and-engineering#1]
## Tips for those who will follow this path!

Leave your tips here too!

**Comment by ericdouglas** [comment]
For the MIT courses, you could find the videos on Youtube, [here](https://www.youtube.com/user/MIT/playlists).

That way, you can increase the speed of the video!

**Comment by ericdouglas** [comment]
In the [Computer Science](https://github.com/ericdouglas/computer-science-and-engineering#computer-science) section, choose one of the introductory courses. You don't need to do all of them.

**Comment by dishark** [comment]
I think we should create a channel where we can discuss with each other.

[Slack](https://slack.com/) is a good option.

**Comment by ericdouglas** [comment]
@dishark  There are two! Look [here](https://github.com/open-source-society/computer-science-and-engineering#community)

**Comment by ramirio** [comment]
I think it would be nice create a educational facebook page so we can add them to the education section of our profile (and let our friends now that this project exist)

**Comment by ericdouglas** [comment]
@ramirio I'll do it! Thanks for pointing that! Would you want to open a new issue for this topic? So I can remeber to do it ASAP!

**Comment by ramirio** [comment]
@ericdouglas fine! #72

**Comment by joseluisq** [comment]
Great initiative !
Thanks :+1:  !

**Comment by yatish27** [comment]
Is there a slack for this ?

**Comment by ericdouglas** [comment]
@yatish27 https://gitter.im/open-source-society/computer-science-and-engineering
