### ISSUE TITLE
Courses about MongoDB

### ISSUE THREAD

**Issue by denpatin** [open-source-society/computer-science-and-engineering#16]
Hi @ericdouglas,

What about adding the [courses concerning MongoDB](https://university.mongodb.com/) to the `Databases` section? They are free.

The only stumbling block is, that not so many people from the whole programmer variety need MongoDB... However, this document-oriented approach does have a right to exist parallel with popular table-based relational structure.

**Comment by mateusz-gorski-hello** [comment]
I don't think there is a place for specializations as this repo serves as aggregation for  concepts rather than tools.

**Comment by denpatin** [comment]
@mateusz-gorski-hello, thanks for expressing your opinion!

Yep, I fully agree with you that this repo is for concepts. Nonetheless, I should state, MongoDB is a concept, too. A document-oriented database concept, which is not covered in the courses that are indicated in the `Database` section.

**Comment by mateusz-gorski-hello** [comment]
I am pretty sure that good course ond databases touches that concept also.

**Comment by denpatin** [comment]
@mateusz-gorski-hello, perhaps, I missed the mentioning of this concept in the descriptions of the courses that are presented in this repo, but still an immersion in such a topic would be pretty useful for any developer. At least it gives more space for planning the architecture of the future application.

**Comment by ericdouglas** [comment]
@denpatin this is a really good course. I learnt a lot with that course, but what @mateusz-gorski-hello makes sense.

What we can do is to create a specialized list for database courses, and add that course in it.

What do you think?

So after the basic graduation, we can have several specialized paths.

**Comment by mateusz-gorski-hello** [comment]
Please, let's not do it. Then this repo will change into "Just a list of some MOOC courses that you may find intersting". later we will start adding books, blogs, videos and it will be crap. There are tons of repos that do that already. Let's not make another one pls.

**Comment by ericdouglas** [comment]
@mateusz-gorski-hello you're totally right! For that reason I tried to just put 3 courses in each category.

Let's stay with it in mind, to preserve the quality of this guide.

Thank you for pointing it!

**Comment by denpatin** [comment]
That's actually a dilemma.

So, I am not proposing to add interesting videos/blogs/whatever, I've just asked for an advice about my assumption that without these courses on MongoDB (at least that one that concerns DBA) the comprehension of the database world wouldn't be fully thorough :smile:

**Comment by ericdouglas** [comment]
@denpatin your suggestion is totally valid, and we can add this course futurely in a specialized list about databases.

**Comment by denpatin** [comment]
@ericdouglas :+1: So I presume we can close this _issue_ :smile_cat:
