### ISSUE TITLE
The IOT courses are not free

### ISSUE THREAD

**Issue by eksperimental** [open-source-society/computer-science-and-engineering#2]
The internet of things' courses are not fre

**Comment by ericdouglas** [comment]
@eksperimental seems that you're right. Generally all the Coursera's courses have the option to enroll without receive a certificate, but those seems that do not have this option.

I'll remove than so. If you find more courses that are not free, please report here!

Many thanks!

**Comment by eksperimental** [comment]
:+1: 
thank you and I will if I ever come across another one
