### ISSUE TITLE
Students Profiles

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/computer-science-and-engineering#28]
### Comment in this issue in order to officially enrolling in our course, and make your public commitment!

Use the following model to create your profile:

```
- **Name**: YOUR NAME
- **GitHub**: [@your_username]()
- **Twitter**: [@your_username]()
- **Linkedin**: [link]()
- **Website**: [yourblog.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()
```

**IMPORTANT**: add your profile once and after you finish each course you can return here and update/edit your comment.

**Comment by ericdouglas** [comment]
- **Name**: Eric Douglas
- **GitHub**: [@ericdouglas](https://github.com/ericdouglas)
- **Twitter**: [@ericdouglas_](https://twitter.com/ericdouglas_)
- **Linkedin**: [link](https://br.linkedin.com/pub/eric-douglas/82/812/813)
- **Website**: [ericdouglas.github.io](http://ericdouglas.github.io/)

# Completed Courses

**Comment by cmbaughman** [comment]
- **Name**: Chris Baughman
- **GitHub**: @cmbaughman
- **Twitter**: @cmbaughman
- **LinkedIn**: [link](https://www.linkedin.com/profile/view?id=18704706)
- **Website**: https://blog.cmb.ninja

## Completed Courses

**Comment by ocrampete16** [comment]
- **Name**: Marco Petersen
- **GitHub**: [@ocrampete16](https://github.com/ocrampete16)
- **Twitter**: [@ocrampete16](https://twitter.com/ocrampete16)
- **Linkedin**: [link](https://www.linkedin.com/in/ocrampete16)
- **Website**: [marcopetersen.net](http://marcopetersen.net)

## Completed Courses

**Comment by monkeynaleo** [comment]
- **Name**: Naleo Hyde
- **GitHub**: [@monkeynaleo]()
- **Twitter**: []()
- **Linkedin**: []()
- **Website**: []()

## Completed Courses

**Name of the Section**

**Comment by ericdouglas** [comment]
@cmbaughman 
@ocrampete16 

#### please add your profile in the issue `#31`. This became very dirty because I referenced it in others issues.

Sorry :sweat_smile:
