### ISSUE TITLE
Huynh Van Tu An

### ISSUE THREAD

**Issue by arishuynhvan** [open-source-society/computer-science-and-engineering#35]
- **Name**: Huynh Van Tu An
- **GitHub**: [@arishuynhvan](https://github.com/arishuynhvan)
- **Twitter**: [@ArisHuang2](https://twitter.com/ArisHuang2)
- **Linkedin**: [link](https://sg.linkedin.com/pub/huynh-van-tu-an/31/795/741)
- **Website**: [TBU]()

## Completed Courses
TBU

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@arishuynhvan 

Can you create your profile in [that](https://github.com/open-source-society/computer-science-and-engineering#becoming-an-oss-student) way?

Thanks!
