### ISSUE TITLE
Enrollment

### ISSUE THREAD

**Issue by datwheat** [open-source-society/computer-science-and-engineering#38]
- **Name**: Jau'n Wheatley
- **GitHub**: [@datwheat]()
- **Twitter**: [@datwheat]()
- **Website**: [datwheat.github.io]()

## Completed Courses

**none**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
Hey, @datwheat !

Can you create your profile in [that](https://github.com/open-source-society/computer-science-and-engineering#becoming-an-oss-student) way?

It's much more easy now! :smile:

Thanks
