### ISSUE TITLE
Missing a datastructures course?

### ISSUE THREAD

**Issue by samrocketman** [open-source-society/computer-science-and-engineering#44]
Need to know about different data structures and how to use them.

**Comment by waterlooSunset** [comment]
Algorithms 1 and Algorithms 2 go into data structures in pretty good depth. Heaps, stack, linked and doubly linked lists, b-trees, etc

**Comment by samrocketman** [comment]
That's good.  I was also looking at this http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-851-advanced-data-structures-spring-2012/

**Comment by ericdouglas** [comment]
@samrocketman what @waterlooSunset resolves this issue, right?!

If you find some MOOC style course, we can add it to the list :smile: 

Thanks for pointing that out!

**Comment by samrocketman** [comment]
@ericdouglas yes, I believe it does based on his description (I have not personally taken the recommended Algorithm courses to verify).
