### ISSUE TITLE
What degree should this be equivalent to?

### ISSUE THREAD

**Issue by NinoScript** [open-source-society/computer-science-and-engineering#45]
I think this is trying to be equivalent to a BS in CS, right?
What would we need to take it one step further into MS territory?

**Comment by ericdouglas** [comment]
Yes, @NinoScript . It's like a BS one, but we have to add some courses to be totally equivalent. Today we are in a pragmatic style, so we have less math courses, zero Physics and Hardware courses, but I plan to add them.

For a MS territory, we need to do another list, and there are several MIT courses about that subject [here](http://ocw.mit.edu/courses/#electrical-engineering-and-computer-science).

We can do those list after finish this one :smile:
