### ISSUE TITLE
Editors

### ISSUE THREAD

**Issue by bsvin33t** [open-source-society/computer-science-and-engineering#51]
I don't see anything related to editors. Being able to use editors efficiently is an essentila part of a programmer's workflow.
Do you think it is a good idea to add content about vim/emacs/sublime/atom?

**Comment by ericdouglas** [comment]
@bsvin33t yes, this is a vital point. Some courses should discuss about it, but I really don't see it as a thing to be added here, because this is too personal.

We need to keep this list as lean as possible.

Anyway, thanks for pointing that out! :smile:
