### ISSUE TITLE
 Student Profile

### ISSUE THREAD

**Issue by Athyrion** [open-source-society/computer-science-and-engineering#52]
- **Name**: Andreas Willems
- **GitHub**: [@athyrion](https://github.com/Athyrion)
- **Twitter**: [@devathyrion](https://twitter.com/devathyrion)
- **Linkedin**: 
- **Website**: 

## Completed Courses

**Comment by ericdouglas** [comment]
Hey, @Athyrion 

Can you create your profile in [that](https://github.com/open-source-society/computer-science-and-engineering#becoming-an-oss-student) way now?

Sorry for that, but in that way will be much more easy for all of us :smile:

**Comment by Athyrion** [comment]
Sure, will do. Sorry for that.

**Comment by ericdouglas** [comment]
@Athyrion no problem! :smile:
