### ISSUE TITLE
Student Profile

### ISSUE THREAD

**Issue by shayankh** [open-source-society/computer-science-and-engineering#53]
- **Name**: Shayan Khan
- **GitHub**: [@shayankh]()
- **Twitter**: None
- **Linkedin**: [https://www.linkedin.com/pub/shayan-khan/7a/70b/5a]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course| [link]()

**Comment by ericdouglas** [comment]
@shayankh 

Can you create your profile in [that](https://github.com/open-source-society/computer-science-and-engineering#becoming-an-oss-student) way now?

Sorry for that, but in that way will be much more easy for all of us :smile:

**Comment by shayankh** [comment]
Is it better now?

**Comment by ericdouglas** [comment]
@shayankh 

you should add your info in the issue `#31`. All students' profiles will be there.
