### ISSUE TITLE
Anwaar Ansari

### ISSUE THREAD

**Issue by anwaaramjad** [open-source-society/computer-science-and-engineering#55]
- **Name**: Anwaar Ansari
- **GitHub**: @anwaaramjad
- **Twitter**: @anwaaramjad

**Comment by ericdouglas** [comment]
@anwaaramjad 

Can you create your profile in [that](https://github.com/open-source-society/computer-science-and-engineering#becoming-an-oss-student) way? On issue `#31`

Sorry for that, but in that way will be much more easy for all of us :smile:
