### ISSUE TITLE
Room for students

### ISSUE THREAD

**Issue by syndbg** [open-source-society/computer-science-and-engineering#56]
I suggest a gitter room to be made where students can chat and help each other out.

**Comment by spetex** [comment]
Someone posted it on reddit, few people are there: https://gitter.im/SerialDev/LearningGrounds

**Comment by ericdouglas** [comment]
@syndbg I'll create one for us

**Comment by ericdouglas** [comment]
Here it is! :smile: 

[![Join the chat at https://gitter.im/open-source-society/computer-science-and-engineering](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/open-source-society/computer-science-and-engineering?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by Ebisu77** [comment]
There is also  [group for OSSU on google groups](https://groups.google.com/forum/#!forum/open-source-society-university)
