### ISSUE TITLE
Michael Mariani 

### ISSUE THREAD

**Issue by ilcapitaan** [open-source-society/computer-science-and-engineering#58]
- **Name**: Michael Mariani
- **GitHub**: [@ilcapitaan]()
- **Twitter**: [@ilcapitaan]()
- **Linkedin**: 
- **Website**: 

## Completed Courses

**Comment by ericdouglas** [comment]
@ilcapitaan 

Can you create your profile in [that](https://github.com/open-source-society/computer-science-and-engineering#becoming-an-oss-student) way? On issue `#31`

 :smile:
