### ISSUE TITLE
Suggestion for Algorithms Course

### ISSUE THREAD

**Issue by rhnvrm** [open-source-society/computer-science-and-engineering#6]
Hi,

I have already done this course from Coursera [Algorithms: Design and Analysis, Part 1](https://www.coursera.org/course/algo) by Tim Roughgarden. Can this also be included in my *Completed Courses* section instead of the one listed in the Algorithms category?

**Comment by ericdouglas** [comment]
Hey, @rhnvrm !

Certainly you can do it! They are equivalents!

:smile:

**Comment by rhnvrm** [comment]
Got it!

**Comment by ericdouglas** [comment]
Awesome @rhnvrm ! :wink:
