### ISSUE TITLE
Open Source Society University

### ISSUE THREAD

**Issue by kennetpostigo** [open-source-society/computer-science-and-engineering#63]
- **Name**: Kennet Postigo
- **GitHub**: [@kennetpostigo]()
- **Twitter**: [@kennetpostigo]()
- **Linkedin**: [Kennet Postigo](https://www.linkedin.com/pub/kennet-postigo/a0/b63/a77)
- **Website**: []()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@kennetpostigo 

Can you create your profile on issue `#31` ?

Thanks! :smile:
