### ISSUE TITLE
Donn K

### ISSUE THREAD

**Issue by Dckstl** [open-source-society/computer-science-and-engineering#64]
- **Name**: Donn K.
- **GitHub**: @dckstl
- **Twitter**: 
- **Linkedin**: 
- **Website**: 

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by mseyne** [comment]
you should post here : 
(https://github.com/open-source-society/computer-science-and-engineering/issues/31)

**Comment by ericdouglas** [comment]
@Dckstl 

yes, you should create your profile on issue `#31` ?

Thanks! :smile:
