### ISSUE TITLE
Tony Dunsworth

### ISSUE THREAD

**Issue by trdunsworth** [open-source-society/computer-science-and-engineering#68]
- **Name**: Tony Dunsworth
- **GitHub**: @trdunsworth
- **Twitter**: @trdunsworth
- **Linkedin**: https://www.linkedin.com/in/tonyrdunsworth
- **Website**: programmeredu.wordpress.com

COMPLETED COURSES

**Comment by dishark** [comment]
Hey @trdunsworth, actually you were supposed to comment that first issue #31 to enroll.

Welcome.
