### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by AzharKanorwala786** [open-source-society/computer-science-and-engineering#77]
Name: Azhar Kanorwala
     GitHub:@AzharKanorwala786
     Twitter:@AzharKanorwala
     Linkedin:https://in.linkedin.com/pub/azhar-kanorwala/79/909/951

## Completed Courses
None Completed

**Comment by ericdouglas** [comment]
@AzharKanorwala786 

add your profile on issue `#31`, please.

Thanks! :smile:

**Comment by AzharKanorwala786** [comment]
Very Sorry
Did not get how to comment on issue..!!

**Comment by ericdouglas** [comment]
@AzharKanorwala786 no problem! :+1:
