### ISSUE TITLE
MOOCs' restriction on sharing?

### ISSUE THREAD

**Issue by Marcelli** [open-source-society/computer-science-and-engineering#84]
Great list, and great idea!
But is it compatible with many MOOCs' rules that you're not allow to share answers to quizes and other exercises outside of the platform (coursera and edx have such restrictions as far as I know).
I personally would like to share my work on exercises, but I don't think that I am allowed to do it.
What do you think?

**Comment by ericdouglas** [comment]
Only share what you can, @Marcelli . Another student had asked it, too.

I'd like to share everything too, but in that case, we need to [be creative](https://github.com/open-source-society/computer-science-and-engineering#be-creative)! :smile:
