### ISSUE TITLE
Ravenstorm Labarcon

### ISSUE THREAD

**Issue by RLabarcon** [open-source-society/computer-science-and-engineering#86]
- **Name**: RAVENSTORM LABARCON
- **GitHub**: [@rlabarcon](https://github.com/RLabarcon)
- **Twitter**: [@TheRavenstorm](https://twitter.com/TheRavenstorm)

## Completed Courses

**Introduction**

Course|Files
:--|:--:
Introduction to Computer Science| [Pending]()
Introduction to Computer Science and Programming Using Python| [Pending]()
Introduction to Computational Thinking and Data Science| [Pending]()

**Comment by ericdouglas** [comment]
@RLabarcon 

can you add your profile on issue `#31`?

Thanks! :smile:
